insert into MATERIAL values(null, 'Cemento', '', 0.75);
insert into MATERIAL values(null, 'Acero', '', 1.70);
insert into MATERIAL values(null, 'Madera', '', 0.10);
insert into MATERIAL values(null, 'Ladrillo', '', 0.25);
insert into MATERIAL values(null, 'Hormigón', '', 0.45);
insert into MATERIAL values(null, 'Plástico', '', 1.80);
insert into MATERIAL values(null, 'Vidrio', '', 0.15);
insert into MATERIAL values(null, 'Teja', '', 0.30);
insert into MATERIAL values(null, 'Aislamiento térmico', '', 0.05);
insert into MATERIAL values(null, 'Aislamiento acústico', '', 0.07);
insert into MATERIAL values(null, 'Concreto ligero', '', 0.35);
insert into MATERIAL values(null, 'Arcilla', '', 0.20);
insert into MATERIAL values(null, 'Piedra natural', '', 0.20);
insert into MATERIAL values(null, 'Teja cerámica', '', 0.25);
insert into MATERIAL values(null, 'Teja metálica', '', 0.40);
insert into MATERIAL values(null, 'Madera contrachapada', '', 0.15);
insert into MATERIAL values(null, 'Madera laminada', '', 0.15);
insert into MATERIAL values(null, 'Aislante de poliestireno expandido', '', 0.03);
insert into MATERIAL values(null, 'Aislante de poliuretano', '', 0.05);